---
galaxy_info:
  role_name: ssh_authorized_keys
  author: Erik Wahlberger
  description: Authorize one or more SSH public keys (personal + automation) for manual and unattended access.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: opensuse
      versions:
        - "all"
  galaxy_tags:
    - ssh
    - automation

dependencies: []
