---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  when: ansible_all_ipv6_addresses

- name: Copy logrotate script
  copy:
    src: "daemon.log"
    dest: "/etc/logrotate.d/daemon.log"
    owner: root
    group: root
    mode: "0755"

- name: Remove logrotate from '/etc/logrotate.d/rsyslog'
  lineinfile:
    path: /etc/logrotate.d/rsyslog
    regex: '^/var/log/daemon\.log'
    state: absent

- name: Create 'cron.minutely' directory
  file:
    path: /etc/cron.minutely
    state: directory

- name: Copy 'logrotate' from 'cron.daily' to 'cron.minutely'
  copy:
    remote_src: true
    src: /etc/cron.daily/logrotate
    dest: /etc/cron.minutely/logrotate

- name: Remove 'logrotate' from 'cron.daily'
  file:
    path: /etc/cron.daily/logrotate
    state: absent

- name: Check if cron.minutely is already defined in crontab
  lineinfile:
    state: absent
    path: "/etc/crontab"
    regexp: "crontab.minutely"
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: check

- name: Define cron.minutely in crontab if not defined
  lineinfile:
    state: present
    path: "/etc/crontab"
    line: "* *    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.minutely )"
  when: check.found == 0

- name: Create /etc/containerd/certs.d directory
  file:
    path: /etc/containerd/certs.d
    mode: 0777
    state: directory

- name: Create /var/lib/rancher/k3s/agent/etc/containerd directory
  file:
    path: /var/lib/rancher/k3s/agent/etc/containerd
    state: directory

- name: Copy containerd configuration template to target
  copy:
    src: "config.toml"
    dest: "/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl"
    mode: "0755"
