---
k3s_version: v1.26.3+k3s1
ansible_user: ansible
systemd_dir: /etc/systemd/system
master_ip: ""
control_plane_ips: []
tls_san: ""
extra_server_args: "--flannel-backend=none --disable-network-policy --cluster-cidr=10.142.0.0/16 --disable traefik --disable servicelb --disable local-storage --tls-san {{ tls_san }}"
extra_agent_args: ""
