#!/bin/bash
USBNAME=`basename $UM_MOUNTPOINT`
SHARENAME=`blkid -s LABEL -o value $UM_DEVICE`
cat > /etc/samba/auto/$USBNAME.conf <<EOF
[$SHARENAME]
   comment = $UM_VENDOR $UM_MODEL
   path = $UM_MOUNTPOINT
   read only = no
   browseable = yes
   guest ok = yes
   guest only = yes
   create mask = 0777
   directory mask = 0777
EOF
 
systemctl restart smbd
systemctl restart nmbd