---
- name: Restart podman.socket
  ansible.builtin.systemd:
    name: podman.socket
    state: restarted
    daemon_reload: true

- name: Restart beszel-agent
  ansible.builtin.systemd:
    name: beszel-agent.service
    state: restarted
    daemon_reload: true
